from termcolors import bcolors

class TextStrings():
    str0 =  F"================================================================================="
    str1 =  F"{bcolors.FAIL}{bcolors.BOLD}ENEMIES ATTACK{bcolors.OKGREEN} Turn No: %s {bcolors.ENDC}"
    str2 =  F"{bcolors.OKGREEN}YOU WIN!{bcolors.ENDC}"
    str3 =  F"{bcolors.FAIL}YOU HAVE LOST!{bcolors.ENDC}"
    str4 =  F"\n\n{bcolors.OKGREEN}Choose action for {bcolors.ENDC}"
    str5 =  F"\n{bcolors.OKGREEN}Choose magic: {bcolors.ENDC}"
    str6 =  F"\n{bcolors.FAIL}Not enough MP!\n{bcolors.ENDC}"
    str7 =  F"\n{bcolors.OKGREEN}Choose Item: {bcolors.ENDC}"
    str8 =  F"{bcolors.FAIL}None Left...{bcolors.ENDC}"
    str9 =  F"{bcolors.WARNING}Press ENTER for next enemy turn.{bcolors.ENDC}"
    str10 = F"\n{bcolors.WARNING}An enemy Ninja has joined the battle! Yikes!{bcolors.ENDC}"
    str11 = F"{bcolors.WARNING}Press ENTER to end battle turn.{bcolors.ENDC}"
    str12 = F"{bcolors.OKBLUE}%s {bcolors.FAIL}has died!{bcolors.ENDC}"
    str13 = F"\n{bcolors.OKBLUE} %s {bcolors.ENDC}casts {bcolors.WARNING}%s{bcolors.ENDC} and self-heals for {bcolors.WARNING}%s{bcolors.ENDC}"
    str14 = F"\n{bcolors.OKBLUE} %s {bcolors.ENDC}uses {bcolors.WARNING}%s{bcolors.ENDC} and self-heals for {bcolors.WARNING}%s{bcolors.ENDC}"
    str15 = F"\n{bcolors.OKBLUE} %s {bcolors.ENDC}uses {bcolors.WARNING}%s{bcolors.ENDC} and fully restores HP & MP!"
    str16 = F"\n{bcolors.BOLD}Choose an action{bcolors.ENDC}"
    str17 = F"\n{bcolors.OKGREEN}Magic:\n{bcolors.ENDC}"
    str18 = F"\n{bcolors.OKGREEN}Items:\n{bcolors.ENDC}"
    str19 = F"\n{bcolors.WARNING}{bcolors.BOLD}ENEMY TARGET SELECTION:{bcolors.ENDC}"
    str20 = F"\n{bcolors.OKGREEN}Choose target: {bcolors.ENDC}"
    str21 = F"{bcolors.BOLD} %s:   %s / %s {bcolors.ENDC}|{bcolors.OKGREEN}%s{bcolors.ENDC}|HP   {bcolors.BOLD}%s / %s  |{bcolors.OKBLUE}%s{bcolors.ENDC}|MP"
    str22 = F"{bcolors.BOLD} %s:   %s / %s {bcolors.ENDC}|{bcolors.FAIL}%s{bcolors.ENDC}|HP   {bcolors.BOLD}%s / %s  |{bcolors.WARNING}%s{bcolors.ENDC}|MP"
    str23 = F"\n{bcolors.OKBLUE}%s {bcolors.ENDC}attacked {bcolors.OKBLUE}%s {bcolors.ENDC}and deals {bcolors.FAIL}%s{bcolors.ENDC} points of damage.{bcolors.ENDC}"
    str24 = F"\n{bcolors.OKBLUE}%s {bcolors.ENDC}casts {bcolors.WARNING}%s {bcolors.ENDC}and deals {bcolors.FAIL}%s{bcolors.ENDC} points of damage to {bcolors.OKBLUE}%s{bcolors.ENDC}."
    str25 = F"\n{bcolors.OKBLUE}%s {bcolors.ENDC}used {bcolors.WARNING}%s {bcolors.ENDC}and deals {bcolors.FAIL}%s{bcolors.ENDC} points of damage to {bcolors.OKBLUE}%s{bcolors.ENDC}."
    str26 = F"{bcolors.FAIL}Attack{bcolors.ENDC}"
    str27 = F"{bcolors.OKGREEN}Magic{bcolors.ENDC}"
    str28 = F"{bcolors.WARNING}Items{bcolors.ENDC}"
    str29 = F"{bcolors.BOLD}%s{bcolors.ENDC}.{bcolors.WARNING} %s{bcolors.ENDC} {bcolors.OKBLUE}(cost %s){bcolors.ENDC}"
    str30 = F"{bcolors.BOLD}%s{bcolors.ENDC}.{bcolors.WARNING} %s{bcolors.ENDC} {bcolors.OKBLUE}(x%s){bcolors.ENDC}  --- %s"